import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

interface SeartchCatImage{
  id: string;
  url: string;
  width: number;
  heigth: number;
}

interface IndexPageProps{
initialCatImageUrl : string;
}




export default function Home() {

  const [catImageUrl, setCatImageUrl] = useState("");


  const fetchCatImage = async() :Promise<SeartchCatImage> =>{
    const res = await fetch("https://api.thecatapi.com/v1/images/search");
    const result = await res.json();
    // console.log(result[0]);
    return result[0];
  };

  const handleClick = async() => {
    const catImage = await fetchCatImage();
    setCatImageUrl(catImage.url);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <h1>猫画像アプリ</h1>
      <div className={styles.img}>
      <img src={catImageUrl}/>
      </div>
      <button className={styles.btn} onClick={handleClick}>
        今日の猫さん
        </button>
    </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<IndexPageProps>;